FROM openjdk:22-jdk
WORKDIR /app
COPY target/*.jar app.jar

ARG SPRING_DATA_MONGODB_URI
ARG SPRING_DATA_MONGODB_DATABASE
ARG SPRING_RABBITMQ_HOST
ARG SPRING_RABBITMQ_PORT
ARG SPRING_RABBITMQ_USERNAME
ARG SPRING_RABBITMQ_PASSWORD
ARG SPRING_RABBITMQ_VIRTUAL_HOST
ARG SPRING_RABBITMQ_SSL_ENABLED

ENV SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
ENV SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
ENV SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
ENV SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
ENV SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
ENV SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
ENV SPRING_RABBITMQ_VIRTUAL_HOST=${SPRING_RABBITMQ_VIRTUAL_HOST}
ENV SPRING_RABBITMQ_SSL_ENABLED=${SPRING_RABBITMQ_SSL_ENABLED}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]