apiVersion: v1
kind: Service
metadata:
  name: event-management-service-service
spec:
  selector:
    app: event-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
